pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3004:3004'
        }
    }
    environment {
        CI = 'true'
        NPM_CONFIG_PREFIX = "${env.WORKSPACE}/.npm-global"
        npm_config_cache = "${env.WORKSPACE}/.npm-cache"
        npm_config_userconfig = "${env.WORKSPACE}/.npmrc"
        PATH = "${env.WORKSPACE}/.npm-global/bin:$PATH"
    }

    stages {
        stage('Prepare Environment') {
            steps {
                script {
                    // Set npm global directory and config within the workspace
                    sh 'mkdir -p ${env.NPM_CONFIG_PREFIX}'
                    sh 'mkdir -p ${env.npm_config_cache}'
                    sh 'echo "prefix = ${env.NPM_CONFIG_PREFIX}" > ${env.npm_config_userconfig}'
                }
            }
        }


        stage('Clean npm Cache') {
            steps {
                sh 'npm cache clean --force'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
