pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3004:3004'
        }
    }
    environment {
        CI = 'true'
        NPM_CONFIG_PREFIX = "${env.WORKSPACE}/.npm-global"
    }

    stages {
        stage('Prepare Environment') {
            steps {
                script {
                    // Set npm global directory to a user-accessible directory within the workspace
                    sh 'mkdir -p ${WORKSPACE}/.npm-global'
                    sh 'npm config set prefix ${WORKSPACE}/.npm-global'
                    sh 'export PATH=${WORKSPACE}/.npm-global/bin:$PATH'
                }
            }
        }

        stage('Clean npm Cache') {
            steps {
                sh 'npm cache clean --force'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
